version: "3.8"
services:
  serviceregistry:
    image: venkatdhruv/serviceregistry:0.0.1
    container_name: serviceregistry
    ports:
      - "8761:8761"
  configserver:
    image: venkatdhruv/configserver:0.0.1
    container_name: configserver
    ports:
      - "9296:9296"
    environment:
      - GIT_TOKEN={git_token}
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    depends_on:
      - serviceregistry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9296/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
  cloud-gateway:
    image: venkatdhruv/cloudgateway:0.0.1
    container_name: cloudgateway
    ports:
      - "9090:9090"
    environment:
      - CONFIG_SERVER_URL=http://configserver:9296
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    depends_on:
        configserver:
          condition: service_healthy
        