apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  git_token: ghp_yourgithubtokenhere
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_server_url: http://config-server-svc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  db_host: mysql-0.mysql
