apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_server_address: http://eureka-0.eureka:8761/eureka
  git_token: {git_token}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
data:
  config_server_url: http://config-server-svc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cm
data:
  db_host: mysql-0.mysql
