server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-32264917.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope:
            - internal
            client-id: 0oaoj603rsSKZUOjX5d7
            client-secret: DZY5liFUaumLrEsbQX32MxrI7gn42zV8VWluhKTbM0u3lu3A-w4pwLAcXNYwFnu6
          

resilience4j:
  circuitbreaker:
    instances:
      external:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
        sliding-window-type: COUNT_BASED
        event-consumer-buffer-size: 10

