server:
  port: 9296

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkatdhruv/app-config
          clone-on-start: true
          default-label: main
          username: venkatdhruv
          password: ${GIT_TOKEN}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka} 
  instance:
    prefer-ip-address: true